"""Capability registry and manifest contracts."""

from visionai.capabilities.applications import (
    ALLOWED_APPLICATIONS,
    app_open_manifest,
    make_app_open_handler,
)
from visionai.capabilities.browser import (
    ALLOWED_BROWSER_HOSTS,
    ALLOWED_SITES,
    browser_handlers,
    browser_manifests,
    browser_open_manifest,
    browser_search_manifest,
    default_browser_opener,
    default_browser_policy,
    make_browser_open_handler,
    make_browser_search_handler,
)
from visionai.capabilities.dispatcher import CapabilityHandler, SerializedDispatcher
from visionai.capabilities.manifest import (
    CapabilityManifest,
    IdempotencyMode,
    ParameterSpec,
    ParameterType,
)
from visionai.capabilities.media import (
    ALLOWED_MEDIA_ACTIONS,
    KeyPresser,
    default_key_presser,
    make_media_control_handler,
    media_control_manifest,
    media_handlers,
    media_manifests,
)
from visionai.capabilities.meta import (
    make_system_capabilities_handler,
    make_system_clear_history_handler,
    make_system_help_handler,
    make_system_stop_handler,
    meta_handlers,
    meta_manifests,
    system_capabilities_manifest,
    system_clear_history_manifest,
    system_help_manifest,
    system_stop_manifest,
)
from visionai.capabilities.registry import CapabilityRegistry
from visionai.capabilities.system_info import (
    make_system_battery_handler,
    make_system_date_handler,
    make_system_health_handler,
    make_system_time_handler,
    system_battery_manifest,
    system_date_manifest,
    system_health_manifest,
    system_info_handlers,
    system_info_manifests,
    system_time_manifest,
)

__all__ = [
    "ALLOWED_APPLICATIONS",
    "ALLOWED_BROWSER_HOSTS",
    "ALLOWED_MEDIA_ACTIONS",
    "ALLOWED_SITES",
    "CapabilityHandler",
    "CapabilityManifest",
    "CapabilityRegistry",
    "IdempotencyMode",
    "KeyPresser",
    "ParameterSpec",
    "ParameterType",
    "SerializedDispatcher",
    "app_open_manifest",
    "browser_handlers",
    "browser_manifests",
    "browser_open_manifest",
    "browser_search_manifest",
    "default_browser_opener",
    "default_browser_policy",
    "default_key_presser",
    "make_app_open_handler",
    "make_browser_open_handler",
    "make_browser_search_handler",
    "make_media_control_handler",
    "make_system_battery_handler",
    "make_system_capabilities_handler",
    "make_system_clear_history_handler",
    "make_system_date_handler",
    "make_system_health_handler",
    "make_system_help_handler",
    "make_system_stop_handler",
    "make_system_time_handler",
    "media_control_manifest",
    "media_handlers",
    "media_manifests",
    "meta_handlers",
    "meta_manifests",
    "system_battery_manifest",
    "system_capabilities_manifest",
    "system_clear_history_manifest",
    "system_date_manifest",
    "system_health_manifest",
    "system_help_manifest",
    "system_info_handlers",
    "system_info_manifests",
    "system_stop_manifest",
    "system_time_manifest",
]
